# fly.toml app configuration file generated for faac-backend on 2025-04-26T10:34:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'faac-backend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
